---
title: "Primaquine PK analysis"
author: "James Watson"
date: "5/21/2021"
output: 
  html_document: 
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, cache.comments = FALSE,
                      echo = TRUE, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)
```


```{r}
library(mgcv)
library(survival)
sessionInfo()
```


```{r}
RUN_MODELS=F

pmq_PK = read.csv('BPD_curated.csv')
Combined_Time_Data = read.csv('Time_to_event.csv')
cols = RColorBrewer::brewer.pal(n = 3, name = 'Dark2')
writeLines(sprintf('There are a total of %s unique patients with data', length(unique(pmq_PK$patientid))))
```


```{r time_since_LD, fig.width=10, fig.height=7}
par(mfrow = c(1,2), las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
plot(pmq_PK$time_since_LD, log(pmq_PK$pk_pmq),
     xlab='Time since last dose (hours)',
     ylab = 'log primaquine concentration')
abline(v=quantile(pmq_PK$time_since_LD, probs = c(0.05,.95)),lty=2)
plot(pmq_PK$time_since_LD, log(pmq_PK$pk_cpmq),
     xlab='Time since last dose (hours)',
     ylab = 'log carboxyprimaquine concentration')
abline(v=quantile(pmq_PK$time_since_LD, probs = c(0.05,.95)),lty=2)
```


```{r}
sum(is.na(pmq_PK$pk_cpmq) & is.na(pmq_PK$pk_pmq))
sum(!is.na(pmq_PK$pk_pip) | !is.na(pmq_PK$pk_cq))

ind_rm = pmq_PK$time_since_LD>30 |
  (pmq_PK$time_since_LD>0.5 & pmq_PK$time_since_LD < 18)

writeLines(sprintf('We remove %s data points',
                   sum(ind_rm)))

pmq_PK$pk_cpmq[ind_rm] = NA
pmq_PK$pk_pmq[ind_rm] = NA


writeLines(sprintf('Analysing a total of %s data points from %s patients',
                   nrow(pmq_PK), sum(!duplicated(pmq_PK$patientid))))

print('Number of CPQ samples:')
sum(!is.na(pmq_PK$pk_cpmq))
print('Number of PQ samples:')
sum(!is.na(pmq_PK$pk_pmq))
print('Number of methb samples:')
sum(!is.na(pmq_PK$methb))
print('Number of HCT samples:')
sum(!is.na(pmq_PK$hct0))
print('Number of patients genotyped for CYP2D6:')
sum(!is.na(pmq_PK$ASscore[!duplicated(pmq_PK$patientid)]))
```



```{r}
par(las=1, mfrow=c(1,2))
plot(pmq_PK$age, pmq_PK$dailypmqdose,xlab='Age (years)', 
     ylab='Daily dose (mg)',
     col = pmq_PK$high_dose+1)
plot(pmq_PK$age, pmq_PK$mgkgdose,
     xlab='Age (years)', ylab='Daily dose (mg/kg)', col = pmq_PK$high_dose+1)

sum(!duplicated(pmq_PK$patientid))
table(pmq_PK$age[!duplicated(pmq_PK$patientid)]<=10)
table(pmq_PK$age[!duplicated(pmq_PK$patientid)]<=5)
```

fit models
```{r models}
pmq_PK$ratio=log10(pmq_PK$pk_cpmq)-log10(pmq_PK$pk_pmq)
pmq_PK$patientid = as.factor(pmq_PK$patientid)
if(RUN_MODELS){
  mod_ratio = gam(ratio ~ s(log10(age), k=3)+
                    mgkgdose+partner_drug+time_since_LD+daysonpq+fct+
                    s(patientid, bs = 're'), 
                  data = pmq_PK)
  mod_pmq = gam(log10(pk_pmq) ~ s(log10(age), k=3)+
                  mgkgdose+partner_drug+time_since_LD+daysonpq+fct+
                  s(patientid, bs = 're'), 
                data = pmq_PK)
  mod_cpmq = gam(log10(pk_cpmq) ~ s(log10(age), k=3)+
                   mgkgdose+partner_drug+time_since_LD+daysonpq+fct+
                   s(patientid, bs = 're'), 
                 data = pmq_PK)
  save(mod_ratio, mod_pmq, mod_cpmq, file = 'models.RData')
} else {
  load(file = 'models.RData')
}
```


```{r day7_summary_results}
par(las=1, mfrow=c(2,2), family='serif', cex.lab=1.3, cex.axis=1.3)
plot(log10(pmq_PK$age), pmq_PK$mgkgdose,panel.first=grid(),
     xlab='Age (years)', ylab='Daily dose (mg/kg)',xaxt='n',
     col = cols[pmq_PK$partner_drug+1])
mtext(text = 'A', side = 3, adj = 0, line=2, cex=1.5)
axis(1, at = log10(c(1.5,3,10,30)), labels = c(1.5,3,10,30))
legend('topleft', col=cols[1:2], pch=1,
       legend = c('DHA-piperaquine','Chloroquine'), inset = 0.06)
points(log10(pmq_PK$age), pmq_PK$mgkgdose,
       col = cols[pmq_PK$partner_drug+1])

plot(log10(pmq_PK$age), log10(pmq_PK$pk_pmq), 
     col = cols[pmq_PK$partner_drug+1], xlab='Age (years)', 
     ylab = 'Primaquine (ng/mL)', yaxt='n',
     panel.first=grid(), xaxt='n')
axis(2, at = seq(0,2.5, length.out = 5), 
     labels = round(10^seq(0,2.5, length.out = 5)))
axis(1, at = log10(c(1.5,3,10,30)), labels = c(1.5,3,10,30))
mtext(text = 'B', side = 3, adj = 0, line=2, cex=1.5)

summary(mod_pmq)
lines(log10(1:60), predict(mod_pmq,
                           data.frame(age=1:60,mgkgdose=0.5,
                                      partner_drug=1,daysonpq=1,
                                      time_since_LD=24,fct=0,
                                      patientid=0),
                           exclude = "s(patientid)"),
      lwd=3)
lines(log10(1:60), predict(mod_pmq,
                           data.frame(age=1:60,mgkgdose=1,
                                      partner_drug=1,daysonpq=1,
                                      time_since_LD=24,fct=0,
                                      patientid=0),
                           exclude = "s(patientid)"),
      lwd=3, lty=2)

plot(log10(pmq_PK$age), log10(pmq_PK$pk_cpmq), 
     col = cols[pmq_PK$partner_drug+1], xlab='Age (years)', 
     ylab = 'Carboxyprimaquine (ng/mL)', yaxt='n',
     panel.first=grid(), xaxt='n')
axis(2, at = seq(1,3.5, length.out = 5), 
     labels = round(10^seq(1,3.5, length.out = 5)))
axis(1, at = log10(c(1.5,3,10,30)), labels = c(1.5,3,10,30))
mtext(text = 'C', side = 3, adj = 0, line=2, cex=1.5)


summary(mod_cpmq)
lines(log10(1:60), predict(mod_cpmq,
                           data.frame(age=1:60,mgkgdose=0.5,
                                      partner_drug=1,daysonpq=1,
                                      time_since_LD=24,fct=0,
                                      patientid=0),
                           exclude = "s(patientid)"),
      lwd=3)
predict(mod_cpmq, data.frame(age=c(5,30),
                             mgkgdose=0.5,
                             partner_drug=1,daysonpq=1,
                             time_since_LD=24,fct=0,
                             patientid=0),
        exclude = "s(patientid)")

predict(mod_pmq, data.frame(age=c(5,30),
                            mgkgdose=0.5,
                            partner_drug=1,daysonpq=1,
                            time_since_LD=24,fct=0,
                            patientid=0),
        exclude = "s(patientid)")

lines(log10(1:60), predict(mod_cpmq,
                           data.frame(age=1:60,mgkgdose=1,
                                      partner_drug=1,daysonpq=1,
                                      time_since_LD=24,fct=0,
                                      patientid=0),
                           exclude = "s(patientid)"),
      lwd=3, lty=2)


## Ratio
plot(log10(pmq_PK$age), pmq_PK$ratio,
     panel.first=grid(),yaxt='n',xaxt='n',
     xlab='Age (years)', ylab='Carboxyprimaquine/Primaquine ratio',
     col = cols[pmq_PK$partner_drug+1])
axis(2, at =  seq(0.5,2.5, length.out = 6), 
     labels = round(10^seq(0.5,2.5, length.out = 6)))
axis(1, at = log10(c(1.5,3,10,30)), labels = c(1.5,3,10,30))
mtext(text = 'D', side = 3, adj = 0,line = 2, cex=1.5)

summary(mod_ratio)
lines(log10(1:60), predict(mod_ratio,
                           data.frame(age=1:60,mgkgdose=0.5,
                                      partner_drug=1,daysonpq=1,
                                      time_since_LD=24,fct=0,
                                      patientid=0),
                           exclude = "s(patientid)"),
      lwd=3)
lines(log10(1:60), predict(mod_ratio,
                           data.frame(age=1:60,mgkgdose=1,
                                      partner_drug=1,daysonpq=1,
                                      time_since_LD=24,fct=0,
                                      patientid=0),
                           exclude = "s(patientid)"),
      lwd=3, lty=2)
```



Numbers for precise comparisons
```{r}
out1=predict(mod_cpmq,data.frame(age=c(5,30),mgkgdose=1,
                                 partner_drug=1,daysonpq=1,
                                 time_since_LD=24,fct=0,
                                 patientid=0),
             exclude = "s(patientid)", se.fit = T)
10^(out1$fit[1])/10^(out1$fit[2])
10^(out1$fit[1]+1.96*out1$se.fit[1])/10^(out1$fit[2]-1.96*out1$se.fit[2])
10^(out1$fit[1]-1.96*out1$se.fit[1])/10^(out1$fit[2]+1.96*out1$se.fit[2])
out1=predict(mod_pmq,data.frame(age=c(5,30),mgkgdose=1,
                                partner_drug=1,daysonpq=1,
                                time_since_LD=24,fct=0,
                                patientid=0),
             exclude = "s(patientid)",se.fit = T)
10^(out1$fit[1])/10^(out1$fit[2])
10^(out1$fit[1]+1.96*out1$se.fit[1])/10^(out1$fit[2]-1.96*out1$se.fit[2])
10^(out1$fit[1]-1.96*out1$se.fit[1])/10^(out1$fit[2]+1.96*out1$se.fit[2])
```


```{r}
pmq_PK$log10_CQ[which(pmq_PK$log10_CQ<1)] = NA
pmq_PK$log10_Pip[which(pmq_PK$log10_Pip<1)] = NA

par(mfrow=c(1,2))
hist(pmq_PK$log10_CQ, xlab='log10 CQ+D-CQ concentration',main='')
hist(pmq_PK$log10_Pip, xlab='log10 Pip concentration',main='')

# effect of chloroquine
mod_pmq_CQ = gam(log10(pk_pmq) ~ s(log10(age), k=3)+
                   mgkgdose+time_since_LD+daysonpq+fct+log10_CQ+
                   s(patientid, bs = 're'), 
                 data = pmq_PK)
summary(mod_pmq_CQ)
xx = summary(mod_pmq_CQ)
10^xx$p.coeff['log10_CQ']
round(10^(xx$p.coeff['log10_CQ'] + c(-1,1)*xx$se['log10_CQ']),1)
xx$p.pv['log10_CQ']

mod_cpmq_CQ = gam(log10(pk_cpmq) ~ s(log10(age), k=3)+
                    mgkgdose+time_since_LD+daysonpq+fct+log10_CQ+
                    s(patientid, bs = 're'), 
                  data = pmq_PK)
summary(mod_cpmq_CQ)
xx = summary(mod_cpmq_CQ)
10^xx$p.coeff['log10_CQ']
round(10^(xx$p.coeff['log10_CQ'] + c(-1,1)*xx$se['log10_CQ']),1)
xx$p.pv['log10_CQ']


mod_ratio_CQ = gam(ratio ~ s(log10(age), k=3)+
                     mgkgdose+time_since_LD+daysonpq+fct+log10_CQ+
                     s(patientid, bs = 're'), 
                   data = pmq_PK)
summary(mod_ratio_CQ)
xx = summary(mod_ratio_CQ)
10^xx$p.coeff['log10_CQ']
round(10^(xx$p.coeff['log10_CQ'] + c(-1,1)*xx$se['log10_CQ']),1)
xx$p.pv['log10_CQ']


# effect of piperaquine
mod_pmq_Pip = gam(log10(pk_pmq) ~ s(log10(age), k=3)+
                    mgkgdose+time_since_LD+daysonpq+fct+log10_Pip, 
                  data = pmq_PK)
summary(mod_pmq_Pip)
xx = summary(mod_pmq_Pip)
10^xx$p.coeff['log10_Pip']
round(10^(xx$p.coeff['log10_Pip'] + c(-1,1)*xx$se['log10_Pip']),1)
xx$p.pv['log10_Pip']

mod_cpmq_Pip = gam(log10(pk_cpmq) ~ s(log10(age), k=3)+
                     mgkgdose+time_since_LD+daysonpq+fct+log10_Pip, 
                   data = pmq_PK)
summary(mod_cpmq_Pip)
xx = summary(mod_cpmq_Pip)
10^xx$p.coeff['log10_Pip']
round(10^(xx$p.coeff['log10_Pip'] + c(-1,1)*xx$se['log10_Pip']),1)
xx$p.pv['log10_Pip']

mod_ratio_Pip = gam(ratio ~ s(log10(age), k=3)+
                      mgkgdose+time_since_LD+daysonpq+fct+log10_Pip, 
                    data = pmq_PK)
summary(mod_ratio_Pip)
```


Supplementary Figure
```{r supplementary_Fig2}
par(las=1, mfrow=c(2,2), family='serif', cex.lab=1.3, cex.axis=1.3)
plot(log10(pmq_PK$pk_pip), log10(pmq_PK$pk_pmq),
     ylab = 'Primaquine (ng/mL)', yaxt='n',
     panel.first=grid(), yaxt='n',xaxt='n',
     xlab = 'Piperaquine (ng/mL)')
axis(2, at = seq(0,2.0, length.out = 5), 
     labels = round(10^seq(0,2, length.out = 5)))
axis(1, at = seq(1,2.2, length.out = 5), 
     labels = round(10^seq(1,2.2, length.out = 5)))
abline(MASS::rlm(log10(pmq_PK$pk_pmq)~log10(pmq_PK$pk_pip)),lty=2)

plot(log10(pmq_PK$pk_pip), log10(pmq_PK$pk_cpmq),
     ylab = 'Carboxyprimaquine (ng/mL)', yaxt='n',
     panel.first=grid(), yaxt='n',xaxt='n',
     xlab = 'Piperaquine (ng/mL)')
axis(2, at = seq(1,3.5, length.out = 5), 
     labels = round(10^seq(1,3.5, length.out = 5)))
axis(1, at = seq(1,2.2, length.out = 5), 
     labels = round(10^seq(1,2.2, length.out = 5)))
abline(MASS::rlm(log10(pmq_PK$pk_cpmq)~log10(pmq_PK$pk_pip)),lty=2)

plot(log10(pmq_PK$pk_cq), log10(pmq_PK$pk_pmq),
     ylab = 'Primaquine (ng/mL)', yaxt='n',
     panel.first=grid(), yaxt='n',xaxt='n',
     xlab = 'Chloroquine (ng/mL)',xlim=c(1,2.31))
axis(2, at = seq(0,2.0, length.out = 5), 
     labels = round(10^seq(0,2, length.out = 5)))
axis(1, at = seq(1,2.2, length.out = 5), 
     labels = round(10^seq(1,2.2, length.out = 5)))
abline(MASS::rlm(log10(pmq_PK$pk_pmq)~log10(pmq_PK$pk_pip)),lty=2)

plot(log10(pmq_PK$pk_cq), log10(pmq_PK$pk_cpmq),
     ylab = 'Carboxyprimaquine (ng/mL)', yaxt='n',
     panel.first=grid(), yaxt='n',xaxt='n',
     xlab = 'Chloroquine (ng/mL)',xlim=c(1,2.31))
axis(2, at = seq(1,3.5, length.out = 5), 
     labels = round(10^seq(1,3.5, length.out = 5)))
axis(1, at = seq(1,2.2, length.out = 5), 
     labels = round(10^seq(1,2.2, length.out = 5)))
abline(MASS::rlm(log10(pmq_PK$pk_cpmq)~log10(pmq_PK$pk_pip)),lty=2)

```


## Figure 2

Plot against residuals******
```{r ASscore_residuals, fig.width=8, fig.height=11}
ind = !is.na(pmq_PK$ASscore)
sum(!duplicated(pmq_PK$patientid) & ind)
table(pmq_PK$ASscore[!duplicated(pmq_PK$patientid)])

pmq_PK$pred_pmq[!is.na(pmq_PK$pk_pmq)] = predict(mod_pmq)
pmq_PK$res_pmq = log10(pmq_PK$pk_pmq)-pmq_PK$pred_pmq

pmq_PK$pred_cpmq[!is.na(pmq_PK$pk_cpmq)] = predict(mod_cpmq)
pmq_PK$res_cpmq = log10(pmq_PK$pk_cpmq)-pmq_PK$pred_cpmq

par(mfrow=c(2,2), las=1, family='serif', 
    cex.axis=1.4, cex.lab=1.4)
layout(mat = matrix(data = c(1,2,3,3),nrow = 2,byrow = T))
boxplot(pmq_PK$res_pmq~pmq_PK$ASscore, 
        xlab='CYP 2D6 activity score',
        varwidth=T,
        ylab='Model residual (primaquine)')
abline(h=0, lty=2, lwd=1)
cor.test(pmq_PK$res_pmq,pmq_PK$ASscore)
mtext(text = 'A', side = 3, adj = 0,line = 2, cex=1.5)

boxplot(pmq_PK$res_cpmq~pmq_PK$ASscore, 
        xlab='CYP 2D6 activity score',
        varwidth=T,
        ylab='Model residual (carboxyprimaquine)')
abline(h=0, lty=2, lwd=1)
# abline(modAS_res_cpmq,lwd=3)
cor.test(pmq_PK$res_cpmq,pmq_PK$ASscore)
mtext(text = 'B', side = 3, adj = 0,line = 2, cex=1.5)

boxplot(pmq_PK$methb ~ pmq_PK$ASscore,
        xlab='CYP 2D6 activity score',
        varwidth=T,
        ylab='Methemoglobin day 7 (%)')
abline(h= c(5,10), lty=2, lwd=1)
modAS_methb = lm(methb ~ ASscore,data = pmq_PK)
cor.test(pmq_PK$methb,as.numeric(pmq_PK$ASscore <1))
mtext(text = 'C', side = 3, adj = 0,line = 2, cex=1.5)

```




## Met-Hb versus age

```{r}
mod_methb = gam(methb ~ s(log10(age),k=3)+
                  mgkgdose+daysonpq+G6PDdef, 
                data = pmq_PK)
xx=summary(mod_methb)
xx$s.pv

out1=predict(mod_methb,data.frame(age=c(5,30),mgkgdose=1,
                                  G6PDdef=1,
                                  daysonpq=1,patientid=0),
             exclude = "s(patientid)",se.fit = T)
(out1$fit[1])/(out1$fit[2])
(out1$fit[1]+1.96*out1$se.fit[1])/(out1$fit[2]-1.96*out1$se.fit[2])
(out1$fit[1]-1.96*out1$se.fit[1])/(out1$fit[2]+1.96*out1$se.fit[2])



mod_methb2 = gam(methb ~ s(log10(age), k=3)+
                   mgkgdose+daysonpq+ASscore+G6PDdef, 
                 data = pmq_PK)
summary(mod_methb2)

mod_methb3 = gam(methb ~ s(log10(age), k=3)+
                   mgkgdose+as.numeric(ASscore<=0.5)+G6PDdef, 
                 data = pmq_PK)
summary(mod_methb3)


which.max(pmq_PK$methb>20)

```


Hb fall
```{r}
pmq_PK$hct_delta = -100*(pmq_PK$hct0 - pmq_PK$hct7)/pmq_PK$hct0
mod_hct_delta = gam(hct_delta ~ s(log10(age),k=3)+
                      mgkgdose+partner_drug+daysonpq+fct+G6PDdef, 
                    data = pmq_PK[pmq_PK$episode==1, ])
summary(mod_hct_delta)
```


Figure 3

```{r metHb}
ids_recurrence = unique(Combined_Time_Data$patientid[Combined_Time_Data$Censored==1])
pmq_PK$recurrence = 1
pmq_PK$recurrence[pmq_PK$patientid %in% ids_recurrence]=16
par(las=1, mfrow=c(2,2), family='serif', 
    cex.axis=1.3, cex.lab=1.3)
plot(log10(pmq_PK$age), pmq_PK$methb,
     xlab='Age (years)', 
     ylab = 'Methemoglobin day 7 (%)',
     panel.first=grid(), xaxt='n',pch=pmq_PK$recurrence)
axis(1, at = log10(c(1.5,3,10,30)), labels = c(1.5,3,10,30))
lines(log10(1:60), predict(mod_methb,
                           data.frame(age=1:60,mgkgdose=0.5,daysonpq=1,
                                      G6PDdef=0)),
      lwd=3)
lines(log10(1:60), predict(mod_methb,
                           data.frame(age=1:60,mgkgdose=1,daysonpq=1,
                                      G6PDdef=0)),
      lwd=3,lty=2)
ind_PM = which(pmq_PK$ASscore<=0.5)

mtext(text = 'A', side = 3, adj = 0,line = 2, cex=1.5)
legend('topleft', pch=c(1,16),
       legend = c('No recurrence','Recurrence'), inset = 0.02)


plot(log10(pmq_PK$age), pmq_PK$hct_delta,
     xlab='Age (years)', 
     ylab = 'Change in hematocrit from baseline (%)',
     panel.first=grid(), xaxt='n',pch=pmq_PK$recurrence)
axis(1, at = log10(c(1.5,3,10,30)), labels = c(1.5,3,10,30))
lines(log10(1:60), predict(mod_hct_delta,
                           data.frame(age=1:60,mgkgdose=0.5,
                                      partner_drug=1,daysonpq=1,
                                      fct=0,G6PDdef=0)),
      lwd=3)
lines(log10(1:60), predict(mod_hct_delta,
                           data.frame(age=1:60,mgkgdose=1,
                                      partner_drug=1,daysonpq=1,
                                      fct=0,G6PDdef=0)),
      lwd=3,lty=2)
mtext(text = 'B', side = 3, adj = 0,line = 2, cex=1.5)

plot(log10(pmq_PK$pk_pmq), pmq_PK$methb,
     xlab='Primaquine day 7 (ng/mL)', 
     ylab = 'Methemoglobin day 7 (%)',
     panel.first=grid(), xaxt='n',pch=pmq_PK$recurrence)
m1=MASS::rlm(pmq_PK$methb~log10(pmq_PK$pk_pmq))
summary(m1)
abline(m1,lwd=3)
axis(1, at = seq(0,2.5, length.out = 5), 
     labels = round(10^seq(0,2.5, length.out = 5)))
mtext(text = 'C', side = 3, adj = 0,line = 2, cex=1.5)

plot(log10(pmq_PK$pk_cpmq), pmq_PK$methb,
     xlab='Carboxyprimaquine day 7 (ng/mL)', 
     ylab = 'Methemoglobin day 7 (%)',
     panel.first=grid(), xaxt='n',pch=pmq_PK$recurrence)
m2=MASS::rlm(pmq_PK$methb~log10(pmq_PK$pk_cpmq))
summary(m2)
abline(m2,lwd=3)
axis(1, at = seq(1,3.5, length.out = 5), 
     labels = round(10^seq(1,3.5, length.out = 5)))
mtext(text = 'D', side = 3, adj = 0,line = 2, cex=1.5)
```


## Recurrence data

```{r}
km_fit = survfit(Surv(Time_to_event, Censored) ~ 1, data=Combined_Time_Data)
plot(km_fit, xlab='time to recurrence')

Combined_Time_Data = Combined_Time_Data[Combined_Time_Data$episode==1 &
                                          !is.na(Combined_Time_Data$CPQ), ]
cox_mod0 <- coxph(Surv(Time_to_event, Censored) ~ PMQ_partner + log10(age) +
                    log10(CPQ)*high_dose_PMQ-high_dose_PMQ, 
                  data = Combined_Time_Data)
summary(cox_mod0)$coefficients

cox_mod1 <- coxph(Surv(Time_to_event, Censored) ~ PMQ_partner + log10(age) +
                    log10(PQ)*high_dose_PMQ-high_dose_PMQ + methb, 
                  data = Combined_Time_Data)
summary(cox_mod1)$coefficients

cox_mod2 <- coxph(Surv(Time_to_event, Censored) ~ PMQ_partner + log10(age) +
                    log10(CPQ)*high_dose_PMQ-high_dose_PMQ + methb, 
                  data = Combined_Time_Data)
summary(cox_mod2)$coefficients
```



## Supplementary Figures


```{r SFigure1}
methb=haven::read_dta('../../Genotyping/Data/PK data/Methb_for James_21Jun.dta')
methb$Visit_ID = apply(methb[, c('patientid','episode','days_elapse')],1,function(x)
  paste(x[1], x[2], x[3], sep='_'))

length(unique(methb$Visit_ID))
methb = methb[!duplicated(methb$Visit_ID), ]
methb = methb[!is.na(methb$methb),]

table(methb$days_elapse)
par(las=1, mfrow=c(1,1), family='serif', cex.axis=1.3, cex.lab=1.3)
ind1=methb$patientid %in% pmq_PK$patientid[pmq_PK$high_dose==0]
methb$high_dose = as.numeric(ind1)
plot(jitter(methb$days_elapse,amount = 0.25), 
     methb$methb, xlim = c(0, 16),
     xlab='Days since start of primaquine', 
     ylab = 'Methemoglobin (%)',
     col = methb$high_dose+1, panel.first=grid())
legend('topright', col = 1:2, 
       legend = c('0.5 mg/kg for 14 days',
                  '1 mg/kg for 7 days'),
       pch = 1, title = 'Primaquine dose',inset=0.02)

special_ids = c(198,301,379,678)
ind = methb$patientid %in% special_ids
plot(methb$days_elapse[ind], methb$methb[ind])
for(id in special_ids){
  ind = methb$patientid ==id
  lines(methb$days_elapse[ind], methb$methb[ind])
  print(methb$methb[ind])
}

pmq_PK$pk_cpmq[pmq_PK$patientid %in% special_ids]
pmq_PK$pk_pmq[pmq_PK$patientid %in% special_ids]
```


